use crate::version::v662::packets::{
    ActorEventPacket, ActorPickRequestPacket, AddActorPacket, AddBehaviourTreePacket,
    AddItemActorPacket, AddPaintingPacket, AddPlayerPacket, AddVolumeEntityPacket,
    AgentActionEventPacket, AgentAnimationPacket, AnimateEntityPacket, AnimatePacket,
    AnvilDamagePacket, AutomationClientConnectPacket, AvailableActorIdentifiersPacket,
    AvailableCommandsPacket, BiomeDefinitionListPacket, BlockActorDataPacket, BlockEventPacket,
    BlockPickRequestPacket, BookEditPacket, BossEventPacket, CameraInstructionPacket, CameraPacket,
    CameraPresetsPacket, CameraShakePacket, ChangeDimensionPacket, ChangeMobPropertyPacket,
    ChunkRadiusUpdatedPacket, ClientBoundDebugRendererPacket, ClientBoundMapItemDataPacket,
    ClientCacheBlobStatusPacket, ClientCacheMissResponsePacket, ClientCacheStatusPacket,
    ClientToServerHandshakePacket, CodeBuilderPacket, CodeBuilderSourcePacket,
    CommandBlockUpdatePacket, CommandOutputPacket, CommandRequestPacket, CompletedUsingItemPacket,
    CompressedBiomeDefinitionListPacket, ContainerClosePacket, ContainerOpenPacket,
    ContainerSetDataPacket, CorrectPlayerMovePredictionPacket, CraftingDataPacket,
    CreatePhotoPacket, CreativeContentPacket, DeathInfoPacket, DebugInfoPacket,
    DimensionDataPacket, DisconnectPacket, EditorNetworkPacket, EduUriResourcePacket,
    EducationSettingsPacket, EmoteListPacket, EmotePacket, FeatureRegistryPacket,
    GameRulesChangedPacket, GameTestRequestPacket, GameTestResultsPacket, GuiDataPickItemPacket,
    HurtArmorPacket, InteractPacket, InventoryContentPacket, InventorySlotPacket,
    InventoryTransactionPacket, ItemComponentPacket, ItemStackRequestPacket,
    ItemStackResponsePacket, LabTablePacket, LecternUpdatePacket, LegacyTelemetryEventPacket,
    LessonProgressPacket, LevelChunkPacket, LevelEventGenericPacket, LevelEventPacket,
    LevelSoundEventPacket, LevelSoundEventPacketV1, LevelSoundEventPacketV2, LoginPacket,
    MapCreateLockedCopyPacket, MapInfoRequestPacket, MobArmorEquipmentPacket, MobEffectPacket,
    MobEquipmentPacket, ModalFormRequestPacket, ModalFormResponsePacket,
    MotionPredictionHintsPacket, MoveActorAbsolutePacket, MoveActorDeltaPacket, MovePlayerPacket,
    MultiplayerSettingsPacket, NetworkChunkPublisherUpdatePacket, NetworkSettingsPacket,
    NetworkStackLatencyPacket, NpcDialoguePacket, NpcRequestPacket, OnScreenTextureAnimationPacket,
    OpenSignPacket, PacketViolationWarningPacket, PassengerJumpPacket, PhotoTransferPacket,
    PlaySoundPacket, PlayStatusPacket, PlayerActionPacket, PlayerArmorDamagePacket,
    PlayerAuthInputPacket, PlayerEnchantOptionsPacket, PlayerFogPacket, PlayerHotbarPacket,
    PlayerInputPacket, PlayerListPacket, PlayerSkinPacket, PlayerStartItemCooldownPacket,
    PlayerToggleCrafterSlotRequestPacket, PositionTrackingDBClientRequestPacket,
    PositionTrackingDBServerBroadcastPacket, PurchaseReceiptPacket, RefreshEntitlementsPacket,
    RemoveActorPacket, RemoveObjectivePacket, RemoveVolumeEntityPacket, RequestAbilityPacket,
    RequestChunkRadiusPacket, RequestNetworkSettingsPacket, RequestPermissionsPacket,
    ResourcePackChunkDataPacket, ResourcePackChunkRequestPacket, ResourcePackClientResponsePacket,
    ResourcePackDataInfoPacket, ResourcePacksInfoPacket, RespawnPacket, ScriptMessagePacket,
    ServerPlayerPostMovePositionPacket, ServerSettingsRequestPacket, ServerSettingsResponsePacket,
    ServerStatsPacket, ServerToClientHandshakePacket, SetActorDataPacket, SetActorLinkPacket,
    SetActorMotionPacket, SetCommandsEnabledPacket, SetDefaultGameTypePacket, SetDifficultyPacket,
    SetDisplayObjectivePacket, SetHealthPacket, SetHudPacket, SetLastHurtByPacket,
    SetLocalPlayerAsInitializedPacket, SetPlayerGameTypePacket, SetPlayerInventoryOptionsPacket,
    SetScorePacket, SetScoreboardIdentityPacket, SetSpawnPositionPacket, SetTimePacket,
    SetTitlePacket, SettingsCommandPacket, ShowCreditsPacket, ShowProfilePacket,
    ShowStoreOfferPacket, SimpleEventPacket, SimulationTypePacket, SpawnExperienceOrbPacket,
    SpawnParticleEffectPacket, StartGamePacket, StopSoundPacket, StructureBlockUpdatePacket,
    StructureDataRequestPacket, StructureDataResponsePacket, SubChunkPacket, SubChunkRequestPacket,
    SubClientLoginPacket, SyncActorPropertyPacket, TakeItemActorPacket, TextPacket, TickSyncPacket,
    TickingAreaLoadStatusPacket, ToastRequestPacket, TransferPlayerPacket, TrimDataPacket,
    UnlockedRecipesPacket, UpdateAbilitiesPacket, UpdateAdventureSettingsPacket,
    UpdateAttributesPacket, UpdateBlockPacket, UpdateBlockSyncedPacket,
    UpdateClientInputLocksPacket, UpdateEquipPacket, UpdateSoftEnumPacket,
    UpdateSubChunkBlocksPacket, UpdateTradePacket,
};
use crate::version::v662::{
    get_gamepacket_header_size_prediction, read_gamepacket_header, write_gamepacket_header,
};
use crate::version::v671::packets::{ResourcePackStackPacket, UpdatePlayerGameTypePacket};
use bedrockrs_macros::gamepackets;
use bedrockrs_proto_core::sub_client::SubClientID;
use std::io::{Cursor, Write};

gamepackets! {
    Login: LoginPacket,
    PlaySatus: PlayStatusPacket,
    ServerToClientHandshake: ServerToClientHandshakePacket,
    ClientToServerHandshake: ClientToServerHandshakePacket,
    Disconnect: DisconnectPacket,
    ResourcePacksInfo: ResourcePacksInfoPacket,
    ResourcePackStack: ResourcePackStackPacket,
    ResourcePackClientResponse: ResourcePackClientResponsePacket,
    Text: TextPacket,
    SetTime: SetTimePacket,
    StartGame: StartGamePacket,
    AddPlayer: AddPlayerPacket,
    AddActor: AddActorPacket,
    RemoveActor: RemoveActorPacket,
    AddItemActor: AddItemActorPacket,
    ServerPlayerPostMovePosition: ServerPlayerPostMovePositionPacket,
    TakeItemActor: TakeItemActorPacket,
    MoveActorAbsolute: MoveActorAbsolutePacket,
    MovePlayer: MovePlayerPacket,
    PassengerJump: PassengerJumpPacket,
    UpdateBlock: UpdateBlockPacket,
    AddPainting: AddPaintingPacket,
    TickSync: TickSyncPacket,
    LevelSoundEventV1: LevelSoundEventPacketV1,
    LevelEvent: LevelEventPacket,
    BlockEvent: BlockEventPacket,
    ActorEvent: ActorEventPacket,
    MobEffect: MobEffectPacket,
    UpdateAttributes: UpdateAttributesPacket,
    InventoryTransaction: InventoryTransactionPacket,
    MobEquipment: MobEquipmentPacket,
    MobArmorEquipment: MobArmorEquipmentPacket,
    Interact: InteractPacket,
    BlockPickRequest: BlockPickRequestPacket,
    ActorPickRequest: ActorPickRequestPacket,
    PlayerAction: PlayerActionPacket,
    HurtArmor: HurtArmorPacket,
    SetActorData: SetActorDataPacket,
    SetActorMotion: SetActorMotionPacket,
    SetActorLink: SetActorLinkPacket,
    SetHealth: SetHealthPacket,
    SetSpawnPosition: SetSpawnPositionPacket,
    Animate: AnimatePacket,
    Respawn: RespawnPacket,
    ContainerOpen: ContainerOpenPacket,
    ContainerClose: ContainerClosePacket,
    PlayerHotbar: PlayerHotbarPacket,
    InventoryContent: InventoryContentPacket,
    InventorySlot: InventorySlotPacket,
    ContainerSetData: ContainerSetDataPacket,
    CraftingData: CraftingDataPacket,
    GuiDataPickItem: GuiDataPickItemPacket,
    BlockActorData: BlockActorDataPacket,
    PlayerInput: PlayerInputPacket,
    LevelChunk: LevelChunkPacket,
    SetCommandsEnabled: SetCommandsEnabledPacket,
    SetDifficulty: SetDifficultyPacket,
    ChangeDimension: ChangeDimensionPacket,
    SetPlayerGameType: SetPlayerGameTypePacket,
    PlayerList: PlayerListPacket,
    SimpleEvent: SimpleEventPacket,
    LegacyTelemetryEvent: LegacyTelemetryEventPacket,
    SpawnExperienceOrb: SpawnExperienceOrbPacket,
    ClientboundMapItemData: ClientBoundMapItemDataPacket,
    MapInfoRequest: MapInfoRequestPacket,
    RequestChunkRadius: RequestChunkRadiusPacket,
    ChunkRadiusUpdated: ChunkRadiusUpdatedPacket,
    GameRulesChanged: GameRulesChangedPacket,
    Camera: CameraPacket,
    BossEvent: BossEventPacket,
    ShowCredits: ShowCreditsPacket,
    AvailableCommands: AvailableCommandsPacket,
    CommandRequest: CommandRequestPacket,
    CommandBlockUpdate: CommandBlockUpdatePacket,
    CommandOutput: CommandOutputPacket,
    UpdateTrade: UpdateTradePacket,
    UpdateEquip: UpdateEquipPacket,
    ResourcePackDataInfo: ResourcePackDataInfoPacket,
    ResourcePackChunkData: ResourcePackChunkDataPacket,
    ResourcePackChunkRequest: ResourcePackChunkRequestPacket,
    TransferPlayer: TransferPlayerPacket,
    PlaySound: PlaySoundPacket,
    StopSound: StopSoundPacket,
    SetTitle: SetTitlePacket,
    AddBehaviourTree: AddBehaviourTreePacket,
    StructureBlockUpdate: StructureBlockUpdatePacket,
    ShowStoreOffer: ShowStoreOfferPacket,
    PurchaseReceipt: PurchaseReceiptPacket,
    PlayerSkin: PlayerSkinPacket,
    SubClientLogin: SubClientLoginPacket,
    AutomationClientConnect: AutomationClientConnectPacket,
    SetLastHurtBy: SetLastHurtByPacket,
    BookEdit: BookEditPacket,
    NpcRequest: NpcRequestPacket,
    PhotoTransfer: PhotoTransferPacket,
    ModalFormRequest: ModalFormRequestPacket,
    ModalFormResponse: ModalFormResponsePacket,
    ServerSettingsRequest: ServerSettingsRequestPacket,
    ServerSettingsResponse: ServerSettingsResponsePacket,
    ShowProfile: ShowProfilePacket,
    SetDefaultGameType: SetDefaultGameTypePacket,
    RemoveObjective: RemoveObjectivePacket,
    SetDisplayObjective: SetDisplayObjectivePacket,
    SetScore: SetScorePacket,
    LabTable: LabTablePacket,
    UpdateBlockSynced: UpdateBlockSyncedPacket,
    MoveActorDelta: MoveActorDeltaPacket,
    SetScoreboardIdentity: SetScoreboardIdentityPacket,
    SetLocalPlayerAsInitialized: SetLocalPlayerAsInitializedPacket,
    UpdateSoftEnum: UpdateSoftEnumPacket,
    NetworkStackLatency: NetworkStackLatencyPacket,
    SpawnParticleEffect: SpawnParticleEffectPacket,
    AvailableActorIdentifiers: AvailableActorIdentifiersPacket,
    LevelSoundEventV2: LevelSoundEventPacketV2,
    NetworkChunkPublisherUpdate: NetworkChunkPublisherUpdatePacket,
    BiomeDefinitionList: BiomeDefinitionListPacket,
    LevelSoundEvent: LevelSoundEventPacket,
    LevelEventGeneric: LevelEventGenericPacket,
    LecternUpdate: LecternUpdatePacket,
    ClientCacheStatus: ClientCacheStatusPacket,
    OnScreenTextureAnimation: OnScreenTextureAnimationPacket,
    MapCreateLockedCopy: MapCreateLockedCopyPacket,
    StructureDataRequest: StructureDataRequestPacket,
    StructureDataResponse: StructureDataResponsePacket,
    ClientCacheBlobStatus: ClientCacheBlobStatusPacket,
    ClientCacheMissResponse: ClientCacheMissResponsePacket,
    EducationSettings: EducationSettingsPacket,
    Emote: EmotePacket,
    MultiplayerSettings: MultiplayerSettingsPacket,
    SettingsCommand: SettingsCommandPacket,
    AnvilDamage: AnvilDamagePacket,
    CompletedUsingItem: CompletedUsingItemPacket,
    NetworkSettings: NetworkSettingsPacket,
    PlayerAuthInput: PlayerAuthInputPacket,
    CreativeContent: CreativeContentPacket,
    PlayerEnchantOptions: PlayerEnchantOptionsPacket,
    ItemStackRequest: ItemStackRequestPacket,
    ItemStackResponse: ItemStackResponsePacket,
    PlayerArmorDamage: PlayerArmorDamagePacket,
    CodeBuilder: CodeBuilderPacket,
    UpdatePlayerGameType: UpdatePlayerGameTypePacket,
    EmoteList: EmoteListPacket,
    PositionTrackingDbServerBroadcast: PositionTrackingDBServerBroadcastPacket,
    PositionTrackingDbClientRequest: PositionTrackingDBClientRequestPacket,
    DebugInfo: DebugInfoPacket,
    PacketViolationWarning: PacketViolationWarningPacket,
    MotionPredictionHints: MotionPredictionHintsPacket,
    AnimateEntity: AnimateEntityPacket,
    CameraShake: CameraShakePacket,
    PlayerFog: PlayerFogPacket,
    CorrectPlayerMovePrediction: CorrectPlayerMovePredictionPacket,
    ItemComponent: ItemComponentPacket,
    ClientboundDebugRenderer: ClientBoundDebugRendererPacket,
    SyncActorProperty: SyncActorPropertyPacket,
    AddVolumeEntity: AddVolumeEntityPacket,
    RemoveVolumeEntity: RemoveVolumeEntityPacket,
    SimulationType: SimulationTypePacket,
    NpcDialogue: NpcDialoguePacket,
    EduUriResource: EduUriResourcePacket,
    CreatePhoto: CreatePhotoPacket,
    UpdateSubChunkBlocks: UpdateSubChunkBlocksPacket,
    SubChunk: SubChunkPacket,
    SubChunkRequest: SubChunkRequestPacket,
    PlayerStartItemCooldown: PlayerStartItemCooldownPacket,
    ScriptMessage: ScriptMessagePacket,
    CodeBuilderSource: CodeBuilderSourcePacket,
    TickingAreaLoadStatus: TickingAreaLoadStatusPacket,
    DimensionData: DimensionDataPacket,
    AgentActionEvent: AgentActionEventPacket,
    ChangeMobProperty: ChangeMobPropertyPacket,
    LessonProgress: LessonProgressPacket,
    RequestAbility: RequestAbilityPacket,
    RequestPermissions: RequestPermissionsPacket,
    ToastRequest: ToastRequestPacket,
    UpdateAbilities: UpdateAbilitiesPacket,
    UpdateAdventureSettings: UpdateAdventureSettingsPacket,
    DeathInfo: DeathInfoPacket,
    EditorNetwork: EditorNetworkPacket,
    FeatureRegistry: FeatureRegistryPacket,
    ServerStats: ServerStatsPacket,
    RequestNetworkSettings: RequestNetworkSettingsPacket,
    GameTestRequest: GameTestRequestPacket,
    GameTestResults: GameTestResultsPacket,
    UpdateClientInputLocks: UpdateClientInputLocksPacket,
    CameraPresets: CameraPresetsPacket,
    UnlockedRecipes: UnlockedRecipesPacket,
    CameraInstruction: CameraInstructionPacket,
    CompressedBiomeDefinitionList: CompressedBiomeDefinitionListPacket,
    TrimData: TrimDataPacket,
    OpenSign: OpenSignPacket,
    AgentAnimation: AgentAnimationPacket,
    RefreshEntitlements: RefreshEntitlementsPacket,
    PlayerToggleCrafterSlotRequest: PlayerToggleCrafterSlotRequestPacket,
    SetPlayerInventoryOptions: SetPlayerInventoryOptionsPacket,
    SetHud: SetHudPacket
}
